"""Generate the paper's pgfplots figures from the committed result records.

Every coordinate is read from results/*/ (the files analyze.py reads), so a
figure cannot disagree with the decision table.  Writes paper/figures/*.tex.

    python scripts/paper_figures.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
R = ROOT / "results"
OUT = ROOT / "paper" / "figures"
PRIOR = 0.25


def L(*p):
    return json.loads(R.joinpath(*p).read_text())


def coords(pairs, err=None):
    if err is None:
        return " ".join(f"({x:.6g},{y:.6g})" for x, y in pairs)
    return " ".join(f"({x:.6g},{y:.6g}) +- (0,{e:.6g})" for (x, y), e in zip(pairs, err))


def friction():
    f = L("exp_f", "results.json")
    ks = f["multipliers"]
    s = []
    for v, style, lab in (("A-std", "blue, mark=square*", "Standard (A-std, $s_\\mathrm{std}$)"),
                          ("A-del", "red, mark=*", "OG-AF (A-del, $s_\\mathrm{del}$)")):
        pm = f["variants"][v]["per_multiplier"]
        pts = [(k, 100 * pm[f"{k:g}"]["point"] / PRIOR) for k in ks]
        err = [100 * (pm[f"{k:g}"]["ci_high"] - pm[f"{k:g}"]["ci_low"]) / 2 / PRIOR for k in ks]
        s.append(f"\\addplot+[{style}, error bars/.cd, y dir=both, y explicit] coordinates {{{coords(pts, err)}}};\n"
                 f"\\addlegendentry{{{lab}}}")
    return ("\\begin{tikzpicture}\\begin{axis}[width=\\linewidth, height=4.6cm, xmode=log, log basis x=2,\n"
            "  xlabel={object friction multiplier (trained at $\\times1$)}, ylabel={IDM error (\\% of prior)},\n"
            "  xtick={0.25,0.5,1,2,4}, xticklabels={0.25,0.5,1,2,4}, ymin=0, ymax=70, grid=major,\n"
            "  legend style={font=\\scriptsize, at={(0.98,0.10)}, anchor=south east}, tick label style={font=\\scriptsize},\n"
            "  label style={font=\\small}]\n" + "\n".join(s) + "\n\\end{axis}\\end{tikzpicture}\n")


def resolution():
    r = L("exp_resolution", "results.json")
    s = []
    for v, style, lab in (("A-std", "blue, mark=square*", "Standard"), ("A-del", "red, mark=*", "OG-AF")):
        bs = [b for b in r["bins"] if v in b]
        pts = [(b["mean_disp_mm"], 100 * b[v]["mean_delta"] / PRIOR) for b in bs]
        err = [100 * (b[v]["ci"][1] - b[v]["ci"][0]) / 2 / PRIOR for b in bs]
        s.append(f"\\addplot+[{style}, error bars/.cd, y dir=both, y explicit] coordinates {{{coords(pts, err)}}};\n"
                 f"\\addlegendentry{{{lab}}}")
    return ("\\begin{tikzpicture}\\begin{axis}[width=\\linewidth, height=4.6cm, xmode=log,\n"
            "  xlabel={settled-position shift caused by the physics change (mm)},\n"
            "  ylabel={$\\Delta$ IDM error (\\% of prior)}, grid=major, ymin=-5, ymax=65,\n"
            "  legend style={font=\\scriptsize, at={(0.02,0.98)}, anchor=north west}, tick label style={font=\\scriptsize},\n"
            "  label style={font=\\small}]\n"
            "\\draw[gray, dashed] (axis cs:4.9,-5) -- (axis cs:4.9,65) node[pos=0.55, right, font=\\tiny] {1 video frame};\n"
            + "\n".join(s) + "\n\\end{axis}\\end{tikzpicture}\n")


def h2():
    z = np.load(R / "exp_h2" / "ladder.npz", allow_pickle=False)
    b, c = "WM-base-100", "WM-physics-corrupted-v2"
    rows = []
    for v in ("standard", "ogaf"):
        inter = 100 * (z[f"{c}_{v}"].mean() - z[f"{b}_{v}"].mean()) / PRIOR
        absent = 100 * (z[f"{c}_ABSENT_{v}"].mean() - z[f"{b}_ABSENT_{v}"].mean()) / PRIOR
        rows.append((v, inter, absent))
    sym = {"standard": "Standard", "ogaf": "OG-AF"}
    inter = " ".join(f"({sym[v]},{i:.3f})" for v, i, _ in rows)
    absent = " ".join(f"({sym[v]},{a:.3f})" for v, _, a in rows)
    return ("\\begin{tikzpicture}\\begin{axis}[width=\\linewidth, height=4.6cm, ybar, bar width=14pt,\n"
            "  symbolic x coords={Standard,OG-AF}, xtick=data, enlarge x limits=0.5, ymin=-5, ymax=58,\n"
            "  ylabel={$\\Delta$ error (\\% of prior)}, grid=major,\n"
            "  nodes near coords={\\pgfmathprintnumber[fixed,precision=1]{\\pgfplotspointmeta}},\n"
            "  nodes near coords style={font=\\tiny, black}, legend columns=1,\n"
            "  legend style={font=\\scriptsize, at={(0.5,1.03)}, anchor=south},\n"
            "  tick label style={font=\\scriptsize}, label style={font=\\small}]\n"
            f"\\addplot+[fill=black!60, draw=black] coordinates {{{inter}}};\\addlegendentry{{INTERACT (physics matters)}}\n"
            f"\\addplot+[fill=black!15, draw=black] coordinates {{{absent}}};\\addlegendentry{{ABSENT (no object: no physics)}}\n"
            "\\end{axis}\\end{tikzpicture}\n")


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, fn in (("friction", friction), ("resolution", resolution), ("h2", h2)):
        (OUT / f"{name}.tex").write_text("% GENERATED by scripts/paper_figures.py from results/ -- do not edit\n" + fn())
        print(f"wrote paper/figures/{name}.tex")
    return 0


if __name__ == "__main__":
    sys.exit(main())
